# Generated by Django 5.0.4 on 2024-06-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='comentario_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Resuelto'), ('3', 'En observación'), ('4', 'Solución rechazada')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='perfil/default.png', upload_to='perfil/'),
        ),
    ]
